version: '2'
services:
  postgres1:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rw_local
      - POSTGRES_USER=rw_local
      - POSTGRES_PASSWORD=rw_local
      - MAX_CONNECTIONS=300
    networks:
      - custom
  event-store:
    image: eventstore/eventstore:22.10.3-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    extra_hosts:
      - "eventstore.com:127.0.0.1"
      - "localhost:127.0.0.1"
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - custom

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
      - "8787:8787"
      - "8882:8882"
    environment:
      STUBBY_PORT: 8882
    volumes:
      - ./realwave-sales-manager-integration/src/test/resources/stubby4j/integration.yml:/usr/local/stubby.yml
    networks:
      - custom

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - custom

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2182"
    networks:
      - custom

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "rw_sm_purchase_events:1:1"
    depends_on:
      - zookeeper
    networks:
      - custom

#  consul:
#    image: consul
#    ports:
#      - 8500:8500
#    networks:
#      - custom

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.167.60.0/16